### ISSUE TITLE
Failed test '.usatoday.com has 2 cookies'

### ISSUE THREAD

**Issue by eserte** [briandfoy/http-cookies-safari#2]
The test suite started to fail:
```
#   Failed test '.usatoday.com has 2 cookies'
#   at t/load.t line 19.
#          got: '2'
#     expected: '3'
# Looks like you failed 1 test of 5.
t/load.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
```

**Comment by briandfoy** [comment]
I've abandoned this module and will not be uploading any further updates. It's primary maintainer is ADOPTME. I should have uploaded a new version saying all that before I gave up the permissions, but oh well.
